name:                wai-session-cookie
version:             0.1.0.0
github:              "alexmingoia/wai-session-cookie"
license:             BSD3
author:              "Alex Mingoia"
maintainer:          "alex@alexmingoia.com"
copyright:           "2022 Alexander C. Mingoia"
category:            Web

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/alexmingoia/wai-session-cookie#readme>

dependencies:
- aeson >= 1.5 && < 1.6
- base >= 4.7 && < 5
- cookie >= 0.4 && < 0.5
- cryptonite >= 0.25 && < 0.28
- base58-bytestring >= 0.1.0 && < 0.2.0
- bytestring >= 0.10 && < 0.11
- http-types >= 0.12 && < 0.13
- random >= 1.2.0 && < 1.3
- time >= 1.8 && < 1.10
- vault >= 0.3 && < 0.4
- wai >= 3.0 && < 3.3

library:
  exposed-modules:
    Network.Wai.Middleware.Session
  source-dirs: src
  default-extensions:
  - OverloadedStrings
